[package]
name = "shadefinder"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.25.0" # managing the xlsx
sun = "0.2.0"


[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
